{% set version = "1.0.2" %}
{% set name = "MOMA" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 01798e936b615c20d8373050d1f7bd2c45e70ba40d2d1e4d6ec9a5ec941fbce5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown, testthat, viper
requirements:
  host:
    - 'bioconductor-complexheatmap >=2.4.0,<2.5.0'
    - 'bioconductor-multiassayexperiment >=1.14.0,<1.15.0'
    - 'bioconductor-qvalue >=2.20.0,<2.21.0'
    - r-base
    - r-circlize
    - r-cluster
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-mkmisc
    - r-rcolorbrewer
    - r-readr
    - r-reshape2
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - 'bioconductor-complexheatmap >=2.4.0,<2.5.0'
    - 'bioconductor-multiassayexperiment >=1.14.0,<1.15.0'
    - 'bioconductor-qvalue >=2.20.0,<2.21.0'
    - r-base
    - r-circlize
    - r-cluster
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-mkmisc
    - r-rcolorbrewer
    - r-readr
    - r-reshape2
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Multi Omic Master Regulator Analysis'
  description: 'This package implements the inference of candidate master regulator proteins from multi-omics'' data (MOMA) algorithm, as well as ancillary analysis and visualization functions.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

