{% set version = "2.16.1" %}
{% set name = "DECIPHER" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 5e85b8fed472ebec5430a148274ed88271aaa141770ca097d59e24821284ff92
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - 'bioconductor-biostrings >=2.56.0,<2.57.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-xvector >=0.28.0,<0.29.0'
    - r-base
    - r-dbi
    - 'r-rsqlite >=1.1'
    - libblas
    - liblapack
  run:
    - 'bioconductor-biostrings >=2.56.0,<2.57.0'
    - 'bioconductor-iranges >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-xvector >=0.28.0,<0.29.0'
    - r-base
    - r-dbi
    - 'r-rsqlite >=1.1'
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Tools for curating, analyzing, and manipulating biological sequences'
  description: 'A toolset for deciphering and managing biological sequences.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:DECIPHER
  parent_recipe:
    name: bioconductor-decipher
    path: recipes/bioconductor-decipher
    version: 2.8.1

