{% set version = "2.4.3" %}
{% set name = "ComplexHeatmap" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b840f8362d0af512ef7fdf089d0dfe115ac6c0fda2e6e9eabb22293af387a0bf
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat (>= 1.0.0), knitr, markdown, dendsort, Cairo, jpeg, tiff, fastcluster, dendextend (>= 1.0.1), grImport, grImport2, glue, GenomicRanges, gridtext
requirements:
  host:
    - r-base
    - 'r-circlize >=0.4.5'
    - r-clue
    - r-colorspace
    - r-getoptlong
    - 'r-globaloptions >=0.1.0'
    - r-png
    - r-rcolorbrewer
  run:
    - r-base
    - 'r-circlize >=0.4.5'
    - r-clue
    - r-colorspace
    - r-getoptlong
    - 'r-globaloptions >=0.1.0'
    - r-png
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Make Complex Heatmaps'
  description: 'Complex heatmaps are efficient to visualize associations between different sources of data sets and reveal potential patterns. Here the ComplexHeatmap package provides a highly flexible way to arrange multiple heatmaps and supports various annotation graphics.'
  license_file: LICENSE
extra:
  identifiers:
    - biotools:complexheatmap
  parent_recipe:
    name: bioconductor-complexheatmap
    path: recipes/bioconductor-complexheatmap
    version: 1.18.1

