{% set version = "1.4.1" %}
{% set name = "CellMixS" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 284cba98c99f5a2bc7d321777876f89e7e42484c5ecda6c18f4c4b1b83571dfe
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown, testthat, limma
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-biocneighbors >=1.6.0,<1.7.0'
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-scater >=1.16.0,<1.17.0'
    - 'bioconductor-singlecellexperiment >=1.10.0,<1.11.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-ggridges
    - r-ksamples
    - r-listarrays
    - r-magrittr
    - r-purrr
    - r-tidyr
    - r-viridis
  run:
    - 'bioconductor-biocgenerics >=0.34.0,<0.35.0'
    - 'bioconductor-biocneighbors >=1.6.0,<1.7.0'
    - 'bioconductor-biocparallel >=1.22.0,<1.23.0'
    - 'bioconductor-scater >=1.16.0,<1.17.0'
    - 'bioconductor-singlecellexperiment >=1.10.0,<1.11.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-base
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-ggridges
    - r-ksamples
    - r-listarrays
    - r-magrittr
    - r-purrr
    - r-tidyr
    - r-viridis
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Evaluate Cellspecific Mixing'
  description: 'Evaluate Cellspecific Mixing Scores (CMS) for different batches/groups in scRNA-seq data.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

