{% set version = "2.14.1" %}
{% set name = "GOSemSim" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 964e9f8409b94a0d6829360ce8fbf97ec01988d6f9af7711c8bd5416724f986c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: AnnotationHub, BiocManager, clusterProfiler, DOSE, knitr, org.Hs.eg.db, prettydoc, testthat
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.50.0,<1.51.0'
    - 'bioconductor-go.db >=3.11.0,<3.12.0'
    - r-base
    - r-rcpp
    - libblas
    - liblapack
  run:
    - 'bioconductor-annotationdbi >=1.50.0,<1.51.0'
    - 'bioconductor-go.db >=3.11.0,<3.12.0'
    - r-base
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'GO-terms Semantic Similarity Measures'
  description: 'The semantic comparisons of Gene Ontology (GO) annotations provide quantitative ways to compute similarities between genes and gene groups, and have became important basis for many bioinformatics analysis approaches. GOSemSim is an R package for semantic similarity computation among GO terms, sets of GO terms, gene products and gene clusters. GOSemSim implemented five methods proposed by Resnik, Schlicker, Jiang, Lin and Wang respectively.'
extra:
  identifiers:
    - biotools:gosemsim
  parent_recipe:
    name: bioconductor-gosemsim
    path: recipes/bioconductor-gosemsim
    version: 2.6.2

