{% set version = "1.4.6" %}
{% set name = "TreeSummarizedExperiment" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: d5b8adfb4ca51968ec06248513a4ea66e396fb1730c580896fc3b7e6d69b089c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: ggtree, BiocStyle, knitr, rmarkdown, testthat
requirements:
  host:
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-singlecellexperiment >=1.10.0,<1.11.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-ape
    - r-base
    - r-dplyr
  run:
    - 'bioconductor-s4vectors >=0.26.0,<0.27.0'
    - 'bioconductor-singlecellexperiment >=1.10.0,<1.11.0'
    - 'bioconductor-summarizedexperiment >=1.18.0,<1.19.0'
    - r-ape
    - r-base
    - r-dplyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'TreeSummarizedExperiment: a S4 Class for Data with Tree Structures'
  description: 'TreeSummarizedExperiment has extended SingleCellExperiment to include hierarchical information on the rows or columns of the rectangular data.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

