{% set version = "1.0.1" %}
{% set name = "GCSConnection" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: cec6ed3a6f5c2c401f39d27fcb2c885e1d6f9b230fa46dfe6b8cfc1e5d9d5c25
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat, knitr, rmarkdown, BiocStyle
requirements:
  host:
    - r-base
    - r-googleauthr
    - r-googlecloudstorager
    - r-httr
    - r-jsonlite
    - 'r-rcpp >=1.0.2'
    - libblas
    - liblapack
  run:
    - r-base
    - r-googleauthr
    - r-googlecloudstorager
    - r-httr
    - r-jsonlite
    - 'r-rcpp >=1.0.2'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Creating R Connection with Google Cloud Storage'
  description: 'Create R ''connection'' objects to google cloud storage buckets using the Google REST interface. Both read and write connections are supported. The package also provide functions to view and manage files on Google Cloud.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

